version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container-bottest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: betbot
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data:/data/db"