environment: ${ENVIRONMENT}

mongodb:
  uri: ${MONGODB_URI}
  driver: ${MONGODB_DRIVER}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  database: 
    diffGols: ${MONGODB_BOT_DIFF_GOLS_DATABASE}
    wins: ${MONGODB_BOT_WINS_DATABASE}

telegram:
  bot:
    diffGols:
      token: ${TELEGRAM_BOT_DIFF_GOLS_TOKEN}
    wins:
      token: ${TELEGRAM_BOT_WINS_TOKEN}
  defaultChatId: ${TELEGRAM_CHAT_ID}

bet:
  url: ${BET_URL}
  apiUrl: ${BET_API_URL}
  apiKey: 
    diffGols: ${BET_BOT_DIFF_GOLS_API_KEY}
    wins: ${BET_BOT_WINS_API_KEY}