mongodb:
  uri: ${MONGODB_URI}
  driver: ${MONGODB_DRIVER}
  database: ${MONGODB_DATABASE}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}

telegram:
  bot:
    diffGols:
      token: ${TELEGRAM_BOT_DIFF_GOLS_TOKEN}
    configuration:
      token: ${TELEGRAM_BOT_CONFIGURATION_TOKEN}
  defaultChatId: ${TELEGRAM_CHAT_ID}

bet:
  url: ${BET_URL}
  apiUrl: ${BET_API_URL}
  apiKey: ${BET_API_KEY}