# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "BET_URL=${{ secrets.BET_URL }}" >> .env
          echo "BET_API_URL=${{ secrets.BET_API_URL }}" >> .env
          echo "BET_API_KEY=${{ secrets.BET_API_KEY }}" >> .env
          echo "MONGODB_DRIVER=${{ secrets.MONGODB_DRIVER }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> .env
          echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> .env
          echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

      - name: Build
        run: npm run clean && tsc

      - name: Commit Build to Branch
        run: |
          git config --global user.email "deyvidrafhael@gmail.com"
          git config --global user.name "Deyvid Spindola"
          git checkout -b build
          git add -f dist
          git commit -m "Add build artifacts"
          git push -f origin build
